openapi: 3.0.0
info:
  title: "Node JS API Project"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schema:
    example:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
paths:
  /:
    get:
      summary: Check API
      description: This api is used to check if services is worked
      responses:
        200:
          description: Access API success
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
              example: { text: "Hello all! using another url for services" }
  /quiz/{material}:
    get:
      tags:
        - Quiz
      summary: Get quiz question
      description: This API is used to get quiz question (Authorization is required)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: material
          description: Path quiz question material desired(relations, alphabet)
          required: true
          schema:
            type: string
            example: relations
        - in: query
          name: count
          description: Query count quiz question (3, 5, etc)
          required: true
          schema:
            type: integer
            example: 5
      response:
        200:
          description: Get quiz question success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/getquiz"
              example:
                {
                  "status": "Success",
                  "message": "Successfully get data",
                  "data":
                    [
                      {
                        "id": 4,
                        "video_url": "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Ibu.webm",
                        "answer1": "Saudara",
                        "answer2": "Kakak",
                        "answer3": "Adik",
                        "answer4": "Ibu",
                      },
                      {
                        "id": 3,
                        "video_url": "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Bibi.webm",
                        "answer1": "Paman",
                        "answer2": "Kakak",
                        "answer3": "Bibi",
                        "answer4": "Ayah",
                      },
                      {
                        "id": 9,
                        "video_url": "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Saudara.webm",
                        "answer1": "Saudara",
                        "answer2": "Paman",
                        "answer3": "Kakek",
                        "answer4": "Ayah",
                      },
                    ],
                }
        401:
          description: Can't find JWT token
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Failed", message: "Can't find JWT token" }
        403:
          description: JWT token invalid
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Forbidden", message: "JWT token invalid" }
    post:
      tags:
        - Quiz
      summary: Post quiz answer
      description: This API is used to post quiz answer (Authorization is required)
      security:
        - bearerAuth: []
      parameters:
        - name: material
          in: path
          description: Path quiz answer material desired(relations, alphabet)
          required: true
          schema:
            type: string
            example: alphabet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              {
                "data":
                  [
                    { "id": 23, "answer": "W" },
                    { "id": 24, "answer": "Z" },
                    { "id": 15, "answer": "O" },
                    { "id": 5, "answer": "E" },
                    { "id": 11, "answer": "K" },
                  ],
              }
      response:
        200:
          description: Post quiz answer success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/postquiz"
              example:
                {
                  "status": "Success",
                  "message": "Successfully get data",
                  "data": { "true_answer": 3, "quiz_length": 5, "score": 60 },
                }
        401:
          description: Can't find JWT token
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Failed", message: "Can't find JWT token" }
        403:
          description: JWT token invalid
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Forbidden", message: "JWT token invalid" }
  /material/{material}:
    get:
      tags:
        - Material
      summary: Get learning materials
      description: This API is used to get learning materials (Authorization is required)
      security:
        - bearerAuth: []
      parameters:
        - name: material
          in: path
          description: Path learning materials (relations, alphabet)
          required: true
          schema:
            type: string
            example: relations
      response:
        200:
          description: Get learning material success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/getmaterialpart"
              example:
                {
                  "status": "Success",
                  "message": "Successfully get data",
                  "data":
                    [
                      {
                        "id": 1,
                        "word": "adik",
                        "video_url": "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Adik.webm",
                      },
                      { "id": 2, "word": "etc", "video_url": "etc" },
                    ],
                }
        401:
          description: Can't find JWT token
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Failed", message: "Can't find JWT token" }
        403:
          description: JWT token invalid
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Forbidden", message: "JWT token invalid" }
  /material/{material}/{submaterial}:
    get:
      tags:
        - Material
      summary: Get one of the learning materials
      description: This API is used to get one of the learning materials (Authorization is required)
      security:
        - bearerAuth: []
      parameters:
        - name: material
          in: path
          description: Path learning materials (relations, alphabet)
          required: true
          schema:
            type: string
            example: relations
        - name: submaterial
          in: path
          description: Path one of the learning materials (ex mother, father or ex a, b)
          required: true
          schema:
            type: string
            example: mother
      response:
        200:
          description: Get one of the learning material success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/getoneofthematerialpart"
              example:
                {
                  "status": "Success",
                  "message": "Successfully get data",
                  "data":
                    {
                      "id": 1,
                      "word": "adik",
                      "video_url": "https://pmpk.kemdikbud.go.id/sibi/SIBI/katadasar/Adik.webm",
                    },
                }
        401:
          description: Can't find JWT token
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Failed", message: "Can't find JWT token" }
        403:
          description: JWT token invalid
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#components/schema/error"
              example: { status: "Forbidden", message: "JWT token invalid" }
